openapi: 3.0.0
paths:
  "/report/reportOne":
    get:
      operationId: getReportOne
      summary: Get first report
      parameters: []
      responses:
        '201':
          description: First report built
          content:
            application/json:
              schema:
                type: string
      tags:
      - report
  "/report/reportTwo":
    get:
      operationId: getReportTwo
      summary: Get second report
      parameters: []
      responses:
        '201':
          description: Second report built
          content:
            application/json:
              schema:
                type: string
      tags:
      - report
info:
  title: CTTI Reports API
  description: CTTI api for reports endpoints
  version: '1.0'
  contact: {}
tags: []
servers:
- url: api
components:
  schemas: {}
